sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: sales of greenweez / we have one row per products_id found in each order id
        columns:
          - name: date_date
            description: the date of purchase
          - name: orders_id
            description: order identifier non unique
          - name: products_id
            description: product identifier non unique
          - name: revenue
            description: item sold for $ excl shipping fee etc
          - name: quantity
            description: number sold of this item
      - name: product
        identifier: raw_gz_product
        description: products of greenweez / we have one row per unique product
        columns:
          - name: products_id
            description: primary key of the table
            tests:
              - unique
          - name: purchase_price
            description: cost of the goods
      - name: ship
        identifier: raw_gz_ship
        description: shipping details
        columns:
          - name: ship_id
            description: shipping identifier

models:
  - name: int_sales_margin
    tests:
      - unique:
          column_name: "(orders_id || '-' || products_id)"
      - not_null:
          column_name:
            - orders_id
            - products_id
            - margin
            - Purchase_cost
            - date_date
            - revenue
            - quantity

  - name: int_orders_margin
    description: margin calcultation per order
    columns:
      - name: order_id
        description: primary key
      - name: margin
        description: Margin = Revenue - Purchase_cost
      - name: Purchase_cost
        description: Purchase_cost = Quantity * Purchase_price
      - name: date_date
        description: date of the order
      - name: revenue
        description: sum of revenue per order
      - name: quantity
        description: sum of quantity per order
